[[build.buildpacks]]
uri = "heroku/deb-packages"

[[build.buildpacks]]
uri = "google.python.runtime"

[[build.buildpacks]]
uri = "google.python.webserver"

[[build.buildpacks]]
uri = "google.utils.label-image"

[com.heroku.buildpacks.deb-packages]
install = [
  "build-essential",
  "gcc",
  "libldap2-dev",
  "libsasl2-dev",
  "libssl-dev",
  "libxml2-dev",
  "libxslt1-dev",
  "libjpeg-dev",
  "zlib1g-dev",
  "libpq-dev",
  "libffi-dev",
  "postgresql-client",
  "node-less",
  "npm",
  "fontconfig",
  "fonts-dejavu-core"
]
