[[build.buildpacks]]
uri = "paketo-buildpacks/apt"

[[build.buildpacks]]
uri = "google.python.runtime"

[[build.buildpacks]]
uri = "google.python.webserver"

[[build.buildpacks]]
uri = "google.python.uv"

[[build.buildpacks]]
uri = "google.utils.label-image"
